### ISSUE TITLE
Not able to connect a new ISAR robot to Flotilla locally

### ISSUE THREAD

**Issue by tsundvoll** [equinor/flotilla#1367]
**Describe the bug**
When trying to connect a new ISAR robot to Flotilla locally, Flotilla gives an error message and the new robot does not show up in the frontend.

**To Reproduce**
1. Start broker with `docker compose up broker`
2. Start Flotilla backend with `dotnet run project --api``
3. Start Flotilla frontend with `npm start`
4. Start isar with isar-robot with `python main.py`

ISAR environment variables:
```
ISAR_ROBOT_NAME="Localbot Huldra"
ISAR_PLANT_SHORT_NAME=hua
ISAR_STID_PLANT_NAME=hua
```

**Expected behavior**
The new robot should show up in the frontend.

**Screenshots**
Flotilla backend gives this error message:
```bash
2024-01-29 08:14:40 - fail: Microsoft.AspNetCore.SignalR.HubConnectionHandler[1]
      => SpanId:267f774a37704ebf, TraceId:dcac42c937d33922d8da31eeaa134f23, ParentId:0000000000000000 => ConnectionId:0HN10J7HCVSE8 => RequestPath:/hub RequestId:0HN10J7HCVSE8:00000007 => TransportConnectionId:uFTi3ttNZh5tdDnujneBLw
      Error when dispatching 'OnConnectedAsync' on hub.
      Microsoft.AspNetCore.SignalR.HubException: Running in development mode, but missing Local__DevUserId value in environment
         at Api.SignalRHubs.SignalRHub.OnConnectedAsync() in /Users/TSUNDV/equinor/flotilla/backend/api/SignalR/SignalRHub.cs:line 28
         at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.OnConnectedAsync(HubConnectionContext connection)
         at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.OnConnectedAsync(HubConnectionContext connection)
         at Microsoft.AspNetCore.SignalR.HubConnectionHandler`1.RunHubAsync(HubConnectionContext connection)
```

**Comment by tsundvoll** [comment]
Was just missing a .env variable, solved
